name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build OpenLauncher
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu
          rid: linux-x64
        - os: windows
          rid: win-x64

    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-restore
    - name: Publish
      working-directory: src/openlauncher
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenLauncher-${{ matrix.rid }}
        path: src/openlauncher/bin/Release/net8.0/${{ matrix.rid }}/publish/**/*
        if-no-files-found: error
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          src/openlauncher/bin/Release/net8.0/${{ matrix.rid }}/publish/openlauncher
          src/openlauncher/bin/Release/net8.0/${{ matrix.rid }}/publish/openlauncher.exe
